# Generated by Django 4.1.7 on 2023-04-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
